{% set name = "pymedphys" %}
{% set version = "0.6.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "5f74ecc8be87977f9a91834b8bd8e68ad8b938933cca64c7d95b93daad8d489d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy>=1.12
    - scipy
    - pandas
    - matplotlib
    - attrs
    - psutil
    - pymssql
    - keyring
    - shapely
    - pydicom>=1.0
    - python-dateutil
    - notebook

test:
  imports:
    - pymedphys

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
