{% set name = "pymedphys" %}
{% set version = "0.8.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23979b662caa7d59936c94883777e73588465dec9aafd4683135f5bd5f86510e

build:
  number: 0
  noarch: python
  script: "python -m pip install . -vvv"
  entry_points:
    - pymedphys = pymedphys.cli.main:pymedphys_cli

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pymedphys_analysis =={{ version }}
    - pymedphys_base =={{ version }}
    - pymedphys_coordsandscales =={{ version }}
    - pymedphys_databases =={{ version }}
    - pymedphys_dicom =={{ version }}
    - pymedphys_electronfactors =={{ version }}
    - pymedphys_fileformats =={{ version }}
    - pymedphys_gamma =={{ version }}
    - pymedphys_labs =={{ version }}
    - pymedphys_logfiles =={{ version }}
    - pymedphys_mudensity =={{ version }}
    - pymedphys_utilities =={{ version }}
    - pymedphys_xlwings =={{ version }}

test:
  imports:
    - pymedphys

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
    - Centrus007
