{% set name = "pymedphys" %}
{% set version = "0.8.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: https://github.com/pymedphys/pymedphys/archive/v{{ version }}.tar.gz
    sha256: 558100b1bb0d290c7be379942c429aba3eeff3d0d62bae2822100b5014b0d7c4

build:
  number: 0
  noarch: python
  entry_points:
    - pymedphys = pymedphys.cli.main:pymedphys_cli
  script: "python -m pip install ./packages/pymedphys --no-deps --ignore-installed --no-cache-dir -vvv"


requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pymedphys_analysis =={{ version }}
    - pymedphys_base =={{ version }}
    - pymedphys_coordsandscales =={{ version }}
    - pymedphys_databases =={{ version }}
    - pymedphys_dicom =={{ version }}
    - pymedphys_electronfactors =={{ version }}
    - pymedphys_fileformats =={{ version }}
    - pymedphys_gamma =={{ version }}
    - pymedphys_labs =={{ version }}
    - pymedphys_logfiles =={{ version }}
    - pymedphys_mudensity =={{ version }}
    - pymedphys_utilities =={{ version }}
    - pymedphys_xlwings =={{ version }}

test:
  imports:
    - pymedphys
    - pymedphys.coordinates
    - pymedphys.dicom
    - pymedphys.electronfactors
    - pymedphys.film
    - pymedphys.gamma
    - pymedphys.geometry
    - pymedphys.logfile
    - pymedphys.mephysto
    - pymedphys.msq
    - pymedphys.mudensity
    - pymedphys.plt
    - pymedphys.trf
    - pymedphys.utilities


outputs:
  - name: pymedphys_analysis
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_analysis --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - pydicom
        - {{ pin_subpackage("pymedphys_dicom", exact=True) }}
        - scipy


  - name: pymedphys_base
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_base --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - numpy >=1.12


  - name: pymedphys_coordsandscales
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_coordsandscales --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - numpy >=1.12


  - name: pymedphys_databases
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_databases --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - attrs
        - keyring
        - numpy >=1.12
        - pandas
        - {{ pin_subpackage("pymedphys_base", exact=True) }}
        - {{ pin_subpackage("pymedphys_fileformats", exact=True) }}
        - {{ pin_subpackage("pymedphys_mudensity", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - pymssql


  - name: pymedphys_dicom
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_dicom --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - packaging
        - pydicom
        - {{ pin_subpackage("pymedphys_base", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}


  - name: pymedphys_electronfactors
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_electronfactors --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - scipy
        - shapely


  - name: pymedphys_fileformats
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_fileformats --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - numpy >=1.12
        - pandas
        - {{ pin_subpackage("pymedphys_base", exact=True) }}


  - name: pymedphys_gamma
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_gamma --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - numpy >=1.12
        - {{ pin_subpackage("pymedphys_dicom", exact=True) }}


  - name: pymedphys_labs
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_labs --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - Pillow
        - matplotlib
        - numpy >=1.12
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - scipy
        - xarray


  - name: pymedphys_logfiles
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_logfiles --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - attrs
        - matplotlib
        - numpy >=1.12
        - pandas
        - {{ pin_subpackage("pymedphys_databases", exact=True) }}
        - {{ pin_subpackage("pymedphys_fileformats", exact=True) }}
        - {{ pin_subpackage("pymedphys_mudensity", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - python-dateutil


  - name: pymedphys_mudensity
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_mudensity --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - {{ pin_subpackage("pymedphys_base", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}


  - name: pymedphys_utilities
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_utilities --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - numpy >=1.12


  - name: pymedphys_xlwings
    build:
      script: 
        - "python -m pip install ./packages/pymedphys_xlwings --no-deps --ignore-installed --no-cache-dir -vvv"
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.7
        - numpy >=1.12
        - pydicom
        - {{ pin_subpackage("pymedphys_dicom", exact=True) }}
        - {{ pin_subpackage("pymedphys_fileformats", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - scipy
        

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: pymedphys/LICENSE-AGPL-3.0-or-later
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
    - Centrus007
