{% set name = "pymedphys" %}
{% set version = "0.2.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9d4f2103a3f10a7f55b3370dc0e342442b6aa0c99165821aaa2118edcb33bb24" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - numba
    - attrs
    - psutil
    - pymssql
    - keyring
    - shapely
    - pydicom

test:
  imports:
    - pymedphys
    - pymedphys.level1
    - pymedphys.level2

about:
  home: https://github.com/CCA-Physics/pymedphys
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics python modules

extra:
  recipe-maintainers:
    - SimonBiggs
