{% set name = "pymedphys" %}
{% set version = "0.8.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: https://github.com/pymedphys/pymedphys/releases/download/v{{ version }}/v{{ version }}.tar.gz
    sha256: 20a5158f605ae9599c94efbb6c30a9be9ba8a3bb99c9079c7ba22b8483d0abd5

build:
  number: 0
  noarch: python
  entry_points:
    - pymedphys = pymedphys.cli.main:pymedphys_cli
  script: "export SUBPACKAGE=pymedphys && yarn conda-forge"


requirements:
  host:
    - python >=3.7
    - pip
    - yarn
  run:
    - python >=3.7
    - {{ pin_subpackage("pymedphys_analysis", exact=True) }}
    - {{ pin_subpackage("pymedphys_base", exact=True) }}
    - {{ pin_subpackage("pymedphys_coordsandscales", exact=True) }}
    - {{ pin_subpackage("pymedphys_databases", exact=True) }}
    - {{ pin_subpackage("pymedphys_dicom", exact=True) }}
    - {{ pin_subpackage("pymedphys_electronfactors", exact=True) }}
    - {{ pin_subpackage("pymedphys_fileformats", exact=True) }}
    - {{ pin_subpackage("pymedphys_gamma", exact=True) }}
    - {{ pin_subpackage("pymedphys_labs", exact=True) }}
    - {{ pin_subpackage("pymedphys_logfiles", exact=True) }}
    - {{ pin_subpackage("pymedphys_mudensity", exact=True) }}
    - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
    - {{ pin_subpackage("pymedphys_xlwings", exact=True) }}


test:
  imports:
    - pymedphys
    - pymedphys.coordinates
    - pymedphys.dicom
    - pymedphys.electronfactors
    - pymedphys.film
    - pymedphys.gamma
    - pymedphys.geometry
    - pymedphys.logfile
    - pymedphys.mephysto
    - pymedphys.msq
    - pymedphys.mudensity
    - pymedphys.plt
    - pymedphys.trf
    - pymedphys.utilities


outputs:
  - name: pymedphys_analysis
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_analysis && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - pydicom
        - {{ pin_subpackage("pymedphys_dicom", exact=True) }}
        - scipy


  - name: pymedphys_base
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_base && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - numpy >=1.12


  - name: pymedphys_coordsandscales
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_coordsandscales && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - numpy >=1.12


  - name: pymedphys_databases
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_databases && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - attrs
        - keyring
        - numpy >=1.12
        - pandas
        - {{ pin_subpackage("pymedphys_base", exact=True) }}
        - {{ pin_subpackage("pymedphys_fileformats", exact=True) }}
        - {{ pin_subpackage("pymedphys_mudensity", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - pymssql


  - name: pymedphys_dicom
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_dicom && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - packaging
        - pydicom
        - {{ pin_subpackage("pymedphys_base", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}


  - name: pymedphys_electronfactors
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_electronfactors && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - scipy
        - shapely


  - name: pymedphys_fileformats
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_fileformats && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - numpy >=1.12
        - pandas
        - {{ pin_subpackage("pymedphys_base", exact=True) }}


  - name: pymedphys_gamma
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_gamma && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - numpy >=1.12
        - {{ pin_subpackage("pymedphys_dicom", exact=True) }}


  - name: pymedphys_labs
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_labs && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - Pillow
        - matplotlib
        - numpy >=1.12
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - scipy
        - xarray


  - name: pymedphys_logfiles
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_logfiles && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - attrs
        - matplotlib
        - numpy >=1.12
        - pandas
        - {{ pin_subpackage("pymedphys_databases", exact=True) }}
        - {{ pin_subpackage("pymedphys_fileformats", exact=True) }}
        - {{ pin_subpackage("pymedphys_mudensity", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - python-dateutil


  - name: pymedphys_mudensity
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_mudensity && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - matplotlib
        - numpy >=1.12
        - {{ pin_subpackage("pymedphys_base", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}


  - name: pymedphys_utilities
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_utilities && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - numpy >=1.12


  - name: pymedphys_xlwings
    build:
      script: 
        - "export SUBPACKAGE=pymedphys_xlwings && yarn conda-forge"
    requirements:
      host:
        - python
        - pip
        - yarn
      run:
        - python >=3.7
        - numpy >=1.12
        - pydicom
        - {{ pin_subpackage("pymedphys_dicom", exact=True) }}
        - {{ pin_subpackage("pymedphys_fileformats", exact=True) }}
        - {{ pin_subpackage("pymedphys_utilities", exact=True) }}
        - scipy


about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: pymedphys/LICENSE-AGPL-3.0-or-later
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
    - Centrus007
