{% set name = "pymedphys" %}
{% set version = "0.8.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b101e957e5a9e44124e58024a2800ea2a3b30617888799efb1d8c974f4937a8

build:
  number: 0
  noarch: python
  script: "python -m pip install . -vvv"
  entry_points:
    - pymedphys = pymedphys.cli.main:pymedphys_cli

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - jinja2
    - notebook
    - pymedphys_analysis==0.8.1
    - pymedphys_base==0.8.1
    - pymedphys_coordsandscales==0.8.1
    - pymedphys_databases==0.8.1
    - pymedphys_dicom==0.8.1
    - pymedphys_electronfactors==0.8.1
    - pymedphys_fileformats==0.8.1
    - pymedphys_gamma==0.8.1
    - pymedphys_labs==0.8.1
    - pymedphys_logfiles==0.8.1
    - pymedphys_mudensity==0.8.1
    - pymedphys_utilities==0.8.1
    - pymedphys_xlwings==0.8.1

test:
  imports:
    - pymedphys

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
    - Centrus007
