{% set name = "pymedphys" %}
{% set version = "0.3.6" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "17309032771f8853bd32621f6373f02040875c5c394b3ba0ee569143f5c34869" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - attrs
    - pymssql
    - keyring
    - shapely
    - pydicom
    - python-dateutil

test:
  imports:
    - pymedphys
    - pymedphys.clobbercheck
    - pymedphys.dcm
    - pymedphys.electronfactors
    - pymedphys.film
    - pymedphys.gamma
    - pymedphys.geometry
    - pymedphys.logfile
    - pymedphys.msq
    - pymedphys.mudensity
    - pymedphys.plt
    - pymedphys.trf
    - pymedphys.type
    - pymedphys.utilities
  requires:
    - pytest
   commands:
    - pytest --pyargs pymedphys

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
