{% set name = "pymedphys" %}
{% set version = "0.8.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0b101e957e5a9e44124e58024a2800ea2a3b30617888799efb1d8c974f4937a8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pymedphys = pymedphys.cli.main:pymedphys_cli

requirements:
  build:
    - python>=3.7
    - pip
  run:
    - attrs
    - keyring
    - matplotlib
    - notebook
    - numpy>=1.12
    - pandas
    - Pillow
    - psutil
    - pydicom>=1.0
    - pymssql
    - python>=3.7
    - python-dateutil
    - scipy
    - shapely
    - xarray

test:
  imports:
    - pymedphys

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
