{% set name = "pymedphys" %}
{% set version = "0.8.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "14e8ecbcad29a8ae952f4e1612911182a3836c5af2ec15c83715a4a576f1ff14" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pymedphys = pymedphys.cli.main:pymedphys_cli

requirements:
  build:
    - python>=3.7
    - pip
  run:
    - jinja2
    - notebook
    - pymedphys_analysis==0.8.1
    - pymedphys_base==0.8.1
    - pymedphys_coordsandscales==0.8.1
    - pymedphys_databases==0.8.1
    - pymedphys_dicom==0.8.1
    - pymedphys_electronfactors==0.8.1
    - pymedphys_fileformats==0.8.1
    - pymedphys_gamma==0.8.1
    - pymedphys_labs==0.8.1
    - pymedphys_logfiles==0.8.1
    - pymedphys_mudensity==0.8.1
    - pymedphys_utilities==0.8.1
    - pymedphys_xlwings==0.8.1

test:
  imports:
    - pymedphys

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
    - Centrus007
