travis:
  secure:
    BINSTAR_TOKEN: MpSlQlHlhYP4Qlp64afspdIrXA24Ud9ljF8iiMIkASM5tY4Jx69kV7gCtFQqESOD7D2c+/qSjGjNfamaPaHcmhrrYadFPBK9F3DGVe6xMN+/ZS0/3+4FfOWHmIhofbjSVVK5hvJNvQ6D+Do/L45lj3Zy0om3x9MtrK27MhX9Ld3JhsiL6EiCpkz6LX0GZvJup+GKPsNKHxmPTcXvaVM5NTYEMr+A8z2pb9iwznszwDupg6caYM1lIH1wgbb/oycxL/jnCzfxaTKFFTsRfjp7z92rSrRdmH43FPKByNNXPGImSh/MKnhA5ZykXKFJgV0Q8s0fRYnxYNlbKHgX+M8N5XeFNBm9N93lqCGA06zXUK8Irh6bUnxL2CVlQ1YJYyviSq0Jd9HPOWdcc8g2PcUT3O5LauBiieH/UGQADoIv+n/D2RFpV2nnRiIvB5PqZIHMI/ah9e8jsH9NwbA/jvuA6jkcWccui47hpY/fIsSNMUjlDikOc9n6sGSbDANbh52B2u50QBBEtf/O5B0Z5rXuMGsQFpBsmsP6zyYYhz2llu0k8C1FOu5HgK81jqa/jcN78dSDejvUP9EfUWK9waty/HNnV7u5nyaVHWWtLmEarmvZRAY0AfUFby4W8ZYwdaVWm146OohYeiJYYFcGCY0EBcri1Fh3kdUzlzKYtmXcYYg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
